version: "2"

services:
  postgres:
    image: postgres:9.4
    networks:
      - projectsecure

  web:
    build: ./
    networks:
      - projectsecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
    command: gunicorn --bind 0.0.0.0:8000  projectsecure.wsgi
    environment:
      DJANGO_SETTINGS_MODULE: projectsecure.settings
      JWT_SECRET_KEY: "A random key"
      SECRET_KEY: "m5rk2z!-z4jx+)w@p!n_y338d56fgtjxob-j^goj7dt6k&f!!!"
      DEBUG: "TRUE"
      HOST: '*'

  nginx:
    build: ./deployment
    depends_on:
      - postgres
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: 192.168.99.100
    networks:
      - projectsecure
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /setup/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  projectsecure:
